### ISSUE TITLE
Directory Purge

### ISSUE THREAD

**Issue by sideshot** [sajal/Cloudfront-Purge-Tool#4]
If you put a directory, will it delete all assets within it?

**Comment by aaronpeters** [comment]
AWS doc about purge on Cloudfront: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html
To purge all in the /images/ directory, the invalidation path must be 
/images/*

**Comment by sideshot** [comment]
gotcha thanks.
